version: '3'

services:
  editor:
    image: ghcr.io/tk42/graphql-editor:latest
    ports: 
     - 8080:3000

  export:
    build:
      context: .
    env_file:
      - .env.local
    volumes:
      - .:/home
